// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3-JZzAgEmzGNFTZB0USCfQRHAIR2K1YI',
    appId: '1:459163704308:web:b0e1b0785a61a9e16077a1',
    messagingSenderId: '459163704308',
    projectId: 'bachelorsapp-8c834',
    authDomain: 'bachelorsapp-8c834.firebaseapp.com',
    storageBucket: 'bachelorsapp-8c834.appspot.com',
    measurementId: 'G-TJ30N0JYGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46DosIASOTuaPO0eqXoivVL7br0FH6WA',
    appId: '1:459163704308:android:c3d6a3c369700f196077a1',
    messagingSenderId: '459163704308',
    projectId: 'bachelorsapp-8c834',
    storageBucket: 'bachelorsapp-8c834.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfF4Da-U4xJ1UUoyo80SO_hRkDQKAwQ8g',
    appId: '1:459163704308:ios:674514a282cb4b496077a1',
    messagingSenderId: '459163704308',
    projectId: 'bachelorsapp-8c834',
    storageBucket: 'bachelorsapp-8c834.appspot.com',
    iosBundleId: 'com.example.bachelorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfF4Da-U4xJ1UUoyo80SO_hRkDQKAwQ8g',
    appId: '1:459163704308:ios:674514a282cb4b496077a1',
    messagingSenderId: '459163704308',
    projectId: 'bachelorsapp-8c834',
    storageBucket: 'bachelorsapp-8c834.appspot.com',
    iosBundleId: 'com.example.bachelorapp',
  );
}
